### PR TITLE
Update builder to generate liferay7 services

### PR DESCRIPTION
**Pull request by nhpatt**
Made some changes to don't have to generate manually a lot of services (I needed ddm, ddl, journal, screens & bookmarks).

Feel free to use it as index of the changes needed to update the builder.

### CODE REVIEW

**Comment by brunofarache** [comment]
Thanks, @nhpatt. As I'm rewriting the Mobile SDK 2.0, I'm also changing the SDK Builder, which will be very different. If you like, I can merge your changes and release a new version but knowing things will change a lot.

**Comment by nhpatt** [comment]
Ok, I did the changes to be quicker implementing the new Liferay 7 services
(we are using about 12 APIs so implementing all of them would be
cumbersome).

The new Mobile SDK 2.0 is scheduled at the same time as Liferay 7 CE, isn't
it? because we wanted to launch Liferay Screens 2.0 more or less at the
same time and we need the new services.

Thanks! :)



Un saludo,

Javier Gamarra

**Comment by brunofarache** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunofarache** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/brunofarache/liferay-mobile-sdk/compare/f5218a1~1...f5218a1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
