### PR TITLE
Cookie authentication

### PR DESCRIPTION
**Pull request by nhpatt**
I think this pull belongs here instead of liferay-mobile repo. I copy the description:

I need two new methods in request to expose follow redirects (to get the auth token for XSS) and media type (to send the login information in the body).

The SignIn method is a bit convoluted... we talked about moving that login to the CookieAuthentication class but it isn't easy because of the asynchronous nature of getting the cookie and token.

### CODE REVIEW

**Comment by brunofarache** [comment]
Thanks @nhpatt! I only saw that now. I'm back from vacation, will review it.

**Comment by nhpatt** [comment]
np :) pretty important reasons for the vacation (congratz!). Take your time, it is the beginning of a conversation about how to implement it, more than the actual finished code.

**Comment by brunofarache** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunofarache** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/brunofarache/liferay-mobile-sdk/compare/14f6d87~6...14f6d87) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunofarache** [comment]
@nhpatt I created a test for it but it's failing. I'm getting from the server:

com.liferay.portal.security.auth.PrincipalException: Invalid authentication token

Can you please check what's wrong? Here's the test class:
https://github.com/brunofarache/liferay-mobile-sdk/blob/master/android/src/test/java/com/liferay/mobile/android/CookieAuthenticationTest.java

**Comment by nhpatt** [comment]
Yes, I'll do :)

**Comment by nhpatt** [comment]
I was trying to reproduce the error (and it seems a relevant error because of the auth token message) but I couldn't :( Against which portal version are you trying?

I did a test against 62, 62 EE & 70 CE with different users but, apart from different sites, all logged in successfully :'(

**Comment by brunofarache** [comment]
interesting @nhpatt. are you running the CookieAuthenticationTest?

I was testing with 6.2 GA 2. Will try with other versions. Thanks for checking it out.

**Comment by nhpatt** [comment]
Yes, I'm running the test, changing the values in test.properties. But I think a portal flag/configuration may be the issue. I've tested only against http://demo.liferay.com/screens/ as a server in "production", the other ones were local servers with minimal properties.

**Comment by brunofarache** [comment]
It seems CookieAuthentication is being created correctly with authToken and cookieHeader. The exception happens when it makes a service call using CookieAuthentication (GroupService.getUserSites()). I will try it out with 7.0 and let you know.

**Pull request closed without merging**
